### ISSUE TITLE
Review installation procedures in various scripts

### ISSUE THREAD

**Issue by datasignals** [frgomes/bash-scripts#19]
We should refrain of cd/pushd all over the place.
In most cases we are doing that just before performing a ``tar``, ``git`` or ``zip`` but all these applications allow passing option `-C` for convenience.

See PR https://github.com/frgomes/bash-scripts/pull/34

**Comment by frgomes** [comment]
Being implemented as part of #57 branch:
https://github.com/frgomes/bash-scripts/tree/feature/0057-overhaul_turn_functions_onto_shell_scripts
