### ISSUE TITLE
can't figure out how to use git_sparse_checkout

### ISSUE THREAD

**Issue by NicolasMICAUX** [frgomes/bash-scripts#64]
hi,
i tested `git_sparse_checkout main git@github.com:NicolasMICAUX/github_test.git -- README.md`
and `git_sparse_checkout git@github.com:NicolasMICAUX/github_test.git -- README.md` but i don't understand the message i get :
`
fatal: impossible de trouver la référence distante master
error: le spécificateur de chemin 'master' ne correspond à aucun fichier connu de git
`

i want to get only `README.md` from the test repo `git@github.com:NicolasMICAUX/github_test.git`

Thanks for your help

**Comment by frgomes** [comment]
@NicolasMICAUX : I've tested this below and works fine for me:

    git_sparse_checkout git@github.com:NicolasMICAUX/github_test.git main github_test -- README.md

**Comment by NicolasMICAUX** [comment]
Thx a lot for your answer. I've used another way of doing it, but it will be useful for next time. Again thank you
